### ISSUE TITLE
Adding Payment Bundles to FOS

### ISSUE THREAD

**Issue by schmittjoh** [FriendsOfSymfony/friendsofsymfony.github.io#2]
Some time back, I've started to create some payment bundles which I'd like to add to the FOS namespace. I'm not sure how much time I'll have to continue working on/maintaining them, but they contain a lot of ground work and would be beneficial for anyone needing payment capabilities in some form.
- https://github.com/schmittjoh/CorePaymentBundle
- https://github.com/schmittjoh/PayPalPaymentBundle

If there is an agreement, I'll change their namespace and move them over to FOS.

**Comment by stof** [comment]
Are they working with the current master ?

I think the payments bundles can be very usefull for many users so I vote +1 if they are up-to-date with Sf2

**Comment by lsmith77** [comment]
I dont have an immediate need. Since you are not working on the code atm, I would suggest we just leave this ticket open and revisit it once one of us is working on the code again.

That point in time could of course be very soon (now). Lets see what the others say. But in principle I can totally see myself needing them down the road.
