### ISSUE TITLE
how to handle branching/merging with BC breaks

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/friendsofsymfony.github.io#27]
so it seems we are adopting different approaches across our bundles which will make it a bit tricky for people to not screw up.

Facebook and Rest are using the Symfony2 approach:
1) bug fixes go to 2.0 branch and get merged to master
2) BC breaks go straight to master

AFAIK Twitter and User are using other models and branch names.

The Symfony2 approach has the advantages that no bug fix can fall through the cracks. But its annoying for users who will likely forget to send their PRs to 2.0. Its also dangerous to merge to master because then we need to do rebase history rewriting hackery. It will also be annoying if we ever say we do not want to provide new features/fixes to an old branch, but then later decide to still do a security commit. But I guess once we retire a branch in such a way we will simply stop targeting it first for bug fixes and instead back port a security fix manually.

Anyway imho we should discuss and agree which approach we want to use and document it once on our github page for reference.

**Comment by stof** [comment]
for your information, I also use the Symfony2 approach in StofDoctrineExtensionsBundle (using a 1.0.x branch as my release number is 1.0 for the first revision of the bundle, not 2.0).

FOSUserBundle uses only one branch currently as it works for both Symfony 2.0 and master. I will soon release 1.1 and then break BC by removing the encoder factory (which is why I wait the release). I'm wondering if I break the BC with Symfony 2.0 at the same time or if I keep 2 different branches without the encoder, as most other todos on FOSUserBundle require Symfony master to implement them cleanly.

FOSTwitterBundle uses 1.0.0 for its first release (which IMO makes more sense that starting at 2.0 as we don't have the same release cycle than Symfony anyway) and so the maintenance branch for this release is logically called 1.0 (or v1.0 maybe). But my idea is to use the same branching model too, even if the branch name is not the same.

Personally, I prefer this workflow over doing all work in master and then cherry-picking to the maintenance branch (the workflow used by Doctrine) as this adds a lot of work to backport fixes.
So IMO, cherry-picking is fine once a branch only receives security fixes but is painful when the branch is still considered as developed.

**Comment by willdurand** [comment]
I'm using a `2.0` branch in PropelBundle as this branch has to be compatible with Symfony2 2.x.x versions. It's bug fixes only and each PR has to be made on this branch at the moment. I merge `2.0` to `master` sometimes.

My 2cent.

**Comment by Crell** [comment]
For comparison, Drupal does it the other way around.  We (almost) always commit everything to the Drupal-next branch first, then backport.  That way we never fix a bug or security hole in stable and then forget to to it in dev, causing a regression.

(Admittedly our BC approach is quite different, but I offer it as a counter-point.)

**Comment by arghav** [comment]
I agree with @stof in starting the version number at 1.0.0 instead of 2.0. At the same time I agree with @lsmith77 that it's a bit confusing to most people. In that case how about we tag releases based on the symfony version it supports?

Lets say tag it `symfony-2.0` and create a branch `symfony-2.0`. It could be pretty obvious for anyone to know which tag or branch to use for the specific version of symfony they are using.

**Comment by stof** [comment]
@kertz the issue is that we don't have the same release cycle than Symfony. For instance, FOSUserBundle 1.0 and 1.1 will work for Symfony 2.0. Naming the first one 2.0 would have lead to an issue for the next one as it would logicall be 2.1 but without the meaning of the symfony version. Using the version of the bundle to indicate the Symfony compatibility kills the semantic versioning of the bundle (and causes issues when a release is still compatible with the next Symfony version).

However, we could consider adding a wiki page in each FOS bundle indicating the compatibility table

@Crell about forgetting to push a fix in the dev branch, this is why the Symfony workflow merges 2.0 into master instead of cherry-picking

**Comment by schmittjoh** [comment]
I'm +1 for @Crell's approach, and backporting fixes where it makes sense.

**Comment by lsmith77** [comment]
@kerz/@stof:
i guess the best way to describe the compatibility at this point is via a composer.json file, so i am ok to move to a tag naming scheme that isn't derived from the Symfony2 version.

@schmittjoh:
what is the advantage of cherry picking?

the way i see it:
advantages of cherry picking:
- most code contributions will target master and so the contributor is less likely to point at the wrong branch
- no need to "pollute" master with commits that revert incompatible changes done to a previous release
  disadvantages of cherry picking:
- very high chance that changes will be forgotten to be back ported

**Comment by stof** [comment]
@lsmith77 composer.json is indeed needed. But I think we need a list for humans somewhere too (because people will probably not look at the different composer.json to find the compatible version)

**Comment by lsmith77** [comment]
it would probably be best to delegate "generating" this list to knpbundles rather than maintaining it by hand.

**Comment by stof** [comment]
yeah, it could be a good solution

**Comment by lsmith77** [comment]
or actually probably http://packagist.org/ should be improved to display this info

**Comment by stof** [comment]
packagist alread displays the dependencies

**Comment by stof** [comment]
but KnpBundles should probably add a feature to filter by supported Symfony version indeed

**Comment by schmittjoh** [comment]
@lsmith77, the advantage of backports to me is that they are explicit. You have no silent breaks by merging an older branch into master (we had a couple of them in symfony). Depending on how often you merge the older branches, you might not even be aware of all the patches that have been made there, and their consequences for the master branch.

I also think that the cherry-picking approach requires less maintenance/coordination, and it might better suite our organisational structure as we have many committers.

**Comment by lsmith77** [comment]
@schmittjoh:
well given my assumption that most of us (and contributors) care about master, i think we will always merge to master right after committing to the old branch, which sort of solves the coordination problem.

on the other hand, especially because i assume that most of us mainly care about master, we will likely start skimming on the back porting.

that being said, maybe we should not even bother ourselves all that much with back porting if we do not personally care about the non master branches. aka if someone does care .. they can always send a PR with the cherry picks.

**Comment by stof** [comment]
@lsmith77 FOS bundles are meant to be good quality bundles so we should definitely maintain actively the branches targeting Symfony 2.0 as most users are using the stable version, not the master branch for Symfony

**Comment by merk** [comment]
Im not fussed with how to manage the backporting, but version wise I think we should list compatibility (for now) in the README.md files. An issue came up in FOSUB today regarding stable versions.

1) Dont name versions based on symfony compatibility
2) Tag compatibility with composer.json - but also push for support with packagist and knpbundles to display this information
3) List branches and tags and their compatibility in the base README.

**Comment by lsmith77** [comment]
ok with me

**Comment by lsmith77** [comment]
oh one issue .. FOSRestBundle isn't really feature complete from my perspective, which is why i never really tagged a version etc .. so i will probably name the branch compatible with Symfony 2.0 something like 0.1

**Comment by arghav** [comment]
Sounds good.

**Comment by stof** [comment]
closing this as our bundles should follow semver now (and we don't have such issues with Symfony BC breaks anymore)
