### ISSUE TITLE
Help to deal with versions in packagist

### ISSUE THREAD

**Issue by diegoholiveira** [FriendsOfSymfony/friendsofsymfony.github.io#36]
Hi folks.

FOSFacebook bundle works only with "minimum-stability" setted as dev. I'm working to change that and make it available as stable for sf2.1 and sf2.2.
What I should do to achieve this? It's just create two branches: v2.1 and v.2.2 or there is another configuration to do on packagist? And I need to make tags too?

Any advise will be welcome. Thanks guys.

**Comment by stof** [comment]
I don't see any reason to have a v2.1 and v2.2 branch when the same code can work for both.
Thus, I don't see any valid reason to start versionning a bundle as 2.0 for its first release. Bundles have a separate release cycle than Symfony. They don't implement features or break BC at the same time, so it makes no sense to synchronize the release numbers.

There is a few missing things in FOSFacebookBundle to make it work properly:
- adding a branch alias for `dev-master` so that the master branch can match requirements looking like `1.1.*` instead of forcing people to depend on unbound constraint
- change the requirement on `facebook/php-sdk` to allow stable releases instead of depending explicitly on `dev-master` (which cannot be fulfilled with stable versions). The constraint should be a range constraint anyway, probably `3.2.*`
- tag the 1.1.0 release of the bundle (a stable version of the bundle can only be a tag. Branches are always dev versions as they can change)

**Comment by diegoholiveira** [comment]
About the itens that you list:
1. How can I adding a branch alias for dev-master?
2. I already change the requirement to allow stable releases (I just not send it yet to github).
3. Should I create a branch called 1.1 and tags like 1.1.x to make it stable?

thanks for the help.

**Comment by stof** [comment]
you don't need a 1.1 branch. The master branch should have a branch alias sayign it is the dev version of 1.1.x See [FOSUserBundle](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/composer.json#L40) for instance

**Comment by stof** [comment]
btw, we have a 1.0.0 tag for symfony 2.0 but the branch is named 2.0. This is a bad idea as composer will consider it as a dev version for 2.0. So I think we should create a 1.0 branch instead (pointing to the same commit) and give some time to people using the 2.0 branch to change their repos before we delete the 2.0 branch, to avoid issues later.

**Comment by diegoholiveira** [comment]
I create a branch called 1.0 pointing to the same commit as 2.0 is pointing.

So, now I'll create on composer.json a branch alias, it's should be like this?

``` json
{
    "extra": {
        "branch-alias": {
            "dev-master": "1.1.x-dev"
        }
    }
}
```

Then I should create a tag called 1.1.0 to make it stable?

**Comment by stof** [comment]
yes, exactly. But take care to change the requirements before tagging.

Btw, I think you should also add a changelog file so that people can know more easily what changed between versions.
