### ISSUE TITLE
scrutinizer

### ISSUE THREAD

**Issue by diegoholiveira** [FriendsOfSymfony/friendsofsymfony.github.io#38]
hi everyone,

there is a common config file for our bundles? If not, we will create one or each project is free to decide your own configuration?

**Comment by stof** [comment]
I think creating a config on scrutinizer which can be used by the different bundles (or inherited in their own config) is a better idea. The structure of the bundles is similar so we would be duplicating the config.

I also vote for using the configuration in scrutinizer rather than adding a file in each bundle as it is supported.
I don't know if the base configs can be shared in an organization or if they are at the developer level though. In the second case, it would require that the same guy enables it for all repos.

**Comment by lsmith77** [comment]
+1 to @stof

**Comment by stof** [comment]
@lsmith77 Actually, we already started to do it. the common config for FOSUserBundle and FOSFacebookBundle is on my account
