### ISSUE TITLE
FOSFacebookBundle

### ISSUE THREAD

**Issue by diegoholiveira** [FriendsOfSymfony/friendsofsymfony.github.io#44]
Guys, sometime ago I took the job of being in charge of FOSFacebookBundle but now I'm not the best person for this job.
The code is stable and work very well, but HWIOAuthBundle provides the same oauth facilities and is much more active.

So, we have two options:
1) Choose someone else to be in charge of FOSFacebookBundle;
2) Deprecate it and recomend everyone to use HWIOAuthBundle.

What do you guys think about it?

**Comment by stof** [comment]
I'm recommending to deprecate it since a long time. None of us is using it, meaning it is impossible to get a decent maintenance on it. and the code is crappy (it duplicates most of the Facebook SdK to handle OAuth to integrate it with the Symfony session IIRC).

My vote is in favor of linking to HWIOAuthBundle

**Comment by lsmith77** [comment]
+1 to deprecate in favor of HWIOAuthBundle

**Comment by willdurand** [comment]
:+1:

**Comment by jmikola** [comment]
:+1:

**Comment by diegoholiveira** [comment]
since no one are in favor of keep FOSFacebookBundle active, I'll change the README recommending the HWIOAuthBundle and a warning saying that the project are deprecated.

**Comment by aitboudad** [comment]
Hi,
I think FOSTwitterBundle must be also deprecate in favor of HWIOAuthBundle https://github.com/FriendsOfSymfony/FOSTwitterBundle/pull/71
